[package]
name = "arcaea_prober_wrapper"
version = "0.1.0"
authors = ["myl7 <myl.ustc@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["size"]
size = ["wee_alloc"]
dev = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
brotli = "3.3"
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
