name = "mylmoe-idea"
type = "javascript"
workers_dev = true
route = "myl.moe/apis/idea"
kv_namespaces = [
    { binding = "MylmoeIdeaNS", id = "353812d4a89a4f36bdc95c9c88c21746", preview_id = "353812d4a89a4f36bdc95c9c88c21746" }
]
