name = "mylmoe-rss"
type = "javascript"
workers_dev = true
kv_namespaces = [
    { binding = "MylmoePostNS", id = "820255000bdd4d568d8cf7bb3327a586", preview_id = "820255000bdd4d568d8cf7bb3327a586" }
]
