name: mainline CI and CD
on:
  push:
    branches:
      - master
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DEPLOY_SCRIPT: ${{ secrets.DEPLOY_SCRIPT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm i
      - name: Test
        run: |
          npm run build
          npm test
      - name: Deploy
        run: |
          npm run build-prod
          echo $SSH_KEY > id_rsa
          chmod 600 id_rsa
          echo $DEPLOY_SCRIPT > deploy.sh
          bash deploy.sh
          rm deploy.sh
          rm id_rsa
